title:              SergioGG!
email:              sergiogogue96@gmail.com
description:        My Portfolio
author:             Sergio González Guerra
baseurl:            ""
url:                "https://sergiogg96.github.io/"

# Social Profiles
twitter_username:   
github_username:  SergioGG96
facebook_username:  
instagram_username:  
linkedin_username: sergio-gonzález-guerra-b21570235

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

collections:
  portfolio:
    output: true
